### PR TITLE
Add veCRV vault

### PR DESCRIPTION
**Pull request by banteg**
A special vault which provides a perpetual claim on Curve admin fees.

Warning: there is no going back after depositing in this vault, all CRV are locked for 4 years and there is no withdrawal functionality.

Curve fee distributor branch: https://github.com/curvefi/curve-dao-contracts/compare/fee-distribution

### CODE REVIEW

**Comment by storming0x** [comment]
This vault has a slightly different pattern from other vaults since it doesnt use the Controller-> strategy delegation, instead uses the Proxy lock directly to transfer CRV balance to StrategyProxy. Implications are that the only logic upgradable is the Proxy itself that can be switched in case of any issues.

**Review by storming0x — APPROVED** [review]
Approving based on reviewed code

**Comment by banteg** [comment]
For users willing to try the vault out:
```python
$ brownie console --network mainnet
user = accounts.load(input('account: '))
deposit = '1000 ether'
yvecrv = Contract.from_explorer('0xc5bDdf9843308380375a611c18B50Fb9341f502A', owner=user)
crv = interface.ERC20(yvecrv.CRV(), owner=user)
crv.approve(yvecrv, deposit)
yvecrv.deposit(deposit)
```

**Comment by banteg** [comment]
Made a simple UI, available at https://crv.ape.tax

Screen Shot 2020-11-07 at 11 53 34

**Pull request merged**
